[mypy]
# Python version
python_version = 3.11

# Strictness configuration
disallow_untyped_defs = False
disallow_incomplete_defs = False
disallow_untyped_decorators = False
check_untyped_defs = False

# Ignore missing imports
ignore_missing_imports = True

# Ignore return type errors
warn_return_any = False
warn_unused_configs = True

# Excluded files and directories
exclude = (?x)(
    ^build/
    | ^dist/
    | ^venv/
    | ^\.venv/
    | ^env/
    | ^\.git/
    | ^__pycache__/
  )

# Report configuration
show_error_codes = True
show_column_numbers = True
show_error_context = True

# Compatible with other tools
# plugins = pydantic.mypy
